Lista de exercicios sobre django Models/core/urls.py
from django.urls import path

from .views import people_list, people_create

app_name = 'core'

urlpatterns = [
    path('list/', people_list, name="lista"),
    path('create/', people_create, name="criar"),
]

Lista de exercicios sobre django Models/peoples/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="home.html")),
    path('admin/', admin.site.urls),
    path('peoples/', include('core.urls')), #tudo que chegar pra peoples/ vai pra core.urls peoples/list (por exemplo)
]

Lista de exercicios sobre django Models/core/models.py
from django.db import models
from dateutil.relativedelta import relativedelta
from datetime import date
import json
#iexact na frente independete maiusculo ou menusculo

class PeopleManager(models.Manager):

    def first_five_people(self):
        return self.model.objects.order_by('nome')[:5]

    def starts_with(self, text):
        return self.model.objects.filter(nome__istartswith=text)

    def para_json(self, ids):
        return self.model.objects.filter(id=ids).values()

    def contem(self, text):
        return self.model.objects.filter(nome__icontains=text)

    def to_json(self, ids):
        data = self.model.objects.filter(id=ids).values()
        data = data[0] #para exibir em formato json
        data['data_nasc'] = data['data_nasc'].isoformat() #type str
        data['altura'] = str(data['altura']) #type str
        return json.dumps(data) #tranforma objetos python em

class People(models.Model):

    GENDER_CHOICES = [
        ("F", "Feminino"), #(banco de dados, Usuario enxerga)
        ("M", "Masculino"),
    ]

    nome = models.CharField(max_length=150)
    cpf = models.CharField(max_length=14)
    rg = models.CharField(max_length=15)
    data_nasc = models.DateField()
    sexo = models.CharField(max_length=1, choices=GENDER_CHOICES)
    mae = models.CharField(max_length=150)
    pai = models.CharField(max_length=150)
    celular = models.CharField(max_length=150)
    altura = models.DecimalField(max_digits=3, decimal_places=2)
    peso = models.PositiveIntegerField()
    tipo_sanguineo = models.CharField(max_length=10)
    endereco = models.CharField(max_length=10, null=True)
    cidade = models.CharField(max_length=10, null=True)
    estado = models.CharField(max_length=10, null=True)
    cep = models.CharField(max_length=10, null=True)
    pais = models.CharField(max_length=10, null=True)
    """
    1. Permitir entrada de dados nulo
    2. Gerar uma migração vazia, e escrever a lógica para popular essa coluna
        nos registros existentes.
    3. Forçar que um valor seja informado para o campo recém criado.
    """

    objects = PeopleManager()

    @property
    def idade(self):
        data_atual = date.today()
        idade = relativedelta(data_atual, self.data_nasc).years
        return idade

    def __str__(self):
        return f"{self.nome} - {self.data_nasc} - {self.idade} anos de idade " #alterando o __str__ da class People

Lista de exercicios sobre django Models/restaurants/models.py
# Referencia: https://docs.djangoproject.com/en/3.2/topics/db/examples/
from django.db import models

class Place(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=80)

    def __str__(self):
        return "%s the place" % self.name


class Restaurant(models.Model):
    place = models.OneToOneField(
        Place,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    serves_hot_dogs = models.BooleanField(default=False)
    serves_pizza = models.BooleanField(default=False)

    def __str__(self):
        return "%s the restaurant" % self.place.name


class Waiter(models.Model):
    restaurant = models.ForeignKey(
        Restaurant, on_delete=models.CASCADE, related_name="qualquercoisa"
    )
    name = models.CharField(max_length=50)

    def __str__(self):
        return "%s the waiter at %s" % (self.name, self.restaurant)

Lista de exercicios sobre django Models/core/forms.py
from django import forms
from core.models import People


class InserePessoaForm(forms.ModelForm):

    class Meta:
        model = People
        fields = "__all__"

Lista de exercicios sobre django Models/core/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from .forms import InserePessoaForm
from django.http import HttpResponseRedirect

from core.models import People


def people_list(request):
    pessoas = People.objects.all()
    context = {
        "pessoas": pessoas
    }
    return render(request, 'core/list2.html', context=context)


def people_create(request):

    if request.method == 'POST':
        form = InserePessoaForm(request.POST)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    else:
        form = InserePessoaForm()

    return render(request, 'core/create.html', context={'form': form})

Lista de exercicios sobre django Models/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    {% block head %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title %}
          <title>Small Business - Start Bootstrap Template</title>
        {% endblock %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    {% endblock %}
    <body>
        <!-- Responsive navbar-->
        {% block navbar %}
          {% include 'partials/_nav.html' %}
        {% endblock %}
        <!-- Page Content-->
        {% block content %}
          <div class="container px-4 px-lg-5">
              <!-- Heading Row-->
              <div class="row gx-4 gx-lg-5 align-items-center my-5">
                  <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="https://dummyimage.com/900x400/dee2e6/6c757d.jpg" alt="..." /></div>
                  <div class="col-lg-5">
                      <h1 class="font-weight-light">Business Name or Tagline</h1>
                      <p>This is a template that is great for small businesses. It doesn't have too much fancy flare to it, but it makes a great use of the standard Bootstrap core components. Feel free to use this template for any project you want!</p>
                      <a class="btn btn-primary" href="#!">Call to Action!</a>
                  </div>
              </div>
              <!-- Call to Action-->
              <div class="card text-white bg-secondary my-5 py-4 text-center">
                  <div class="card-body"><p class="text-white m-0">This call to action card is a great place to showcase some important information or display a clever tagline!</p></div>
              </div>
              <!-- Content Row-->
              <div class="row gx-4 gx-lg-5">
                  <div class="col-md-4 mb-5">
                      <div class="card h-100">
                          <div class="card-body">
                              <h2 class="card-title">Card One</h2>
                              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
                          </div>
                          <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
                      </div>
                  </div>
                  <div class="col-md-4 mb-5">
                      <div class="card h-100">
                          <div class="card-body">
                              <h2 class="card-title">Card Two</h2>
                              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod tenetur ex natus at dolorem enim! Nesciunt pariatur voluptatem sunt quam eaque, vel, non in id dolore voluptates quos eligendi labore.</p>
                          </div>
                          <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
                      </div>
                  </div>
                  <div class="col-md-4 mb-5">
                      <div class="card h-100">
                          <div class="card-body">
                              <h2 class="card-title">Card Three</h2>
                              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
                          </div>
                          <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
                      </div>
                  </div>
              </div>
          </div>
        {% endblock %}
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

Lista de exercicios sobre django Models/templates/core/create.html
{% extends 'base.html' %}

{% block title %}
  <title>Add Pessoa</title>
{% endblock %}

{% block content %}

  <form action="/peoples/create/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
      <input type="submit" value="Submit">
  </form>
{% endblock%}

Lista de exercicios sobre django Models/templates/core/list.html
{% extends 'base.html' %}

{% block title %}
  <title>Listagem de Pessoas</title>
{% endblock %}

{% block content %}
  <h1>Lista de Pessoas</h1>
  {% if pessoas.exists %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Nome</th>
          <th scope="col">Data de Nascimento</th>
          <th scope="col">Tipo Sanguineo</th>
        </tr>
      </thead>
      <tbody>
      {% for p in pessoas %}
        <tr>
          <th scope="row">{{ p.pk }}</th>
          <td>{{ p.nome | upper }}</td>
          <td>{{ p.data_nasc }}</td>
          <td>{{ p.tipo_sanguineo }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>Nada a listar</p>
  {% endif %}
{% endblock %}

Lista de exercicios sobre django Models/templates/home.html
{% extends "base.html" %}

{% block title %}
  <title>Minha Home</title>
{% endblock %}

Lista de exercicios sobre django Models/templates/partials/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="#!">Inova.Ação Afro - CESAR</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:lista' %}">Lista de Pessoas</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:criar' %}">Inserir Pessoas</a>
                </li>
            </ul>
        </div>
    </div>
</nav>